Limit operation types per linkage
bitshares/beet pull request #211
Opened 2022-09-24 18:01 UTC by grctest

Addresses the following issue feature request: https://github.com/bitshares/beet/issues/208

Beet-JS will also need to update to reflect the introduction of requested operation types in link attempts.

2022-09-25 20:53 UTC, sschiessl-bcp requested changes

2022-09-25 20:53 UTC, sschiessl-bcp commented on src/components/popups/linkrequestpopup.vue
> +            return types.map(type => `${type.id}: ${type.method.method.replaceAll("_", " ")}`);
I assume the list of requested operations in an app that is actually using that feature is quite short. In the case of all permissions, I would rather use a keyword "all" or similar. A user will not review a list of 50+ ops, or try to differentiate if another app actually requrests "only" 49 ...

Thoughts?

2022-09-25 20:53 UTC, sschiessl-bcp commented on src/components/popups/linkrequestpopup.vue
> +            return types.map(type => `${type.id}: ${type.method.method.replaceAll("_", " ")}`);
This is also specific to the injection call, correct? So the other defined calls directly baked into beet (like transfer), are always allowed as well?

2022-09-25 21:05 UTC, grctest commented on src/components/popups/linkrequestpopup.vue
> +            return types.map(type => `${type.id}: ${type.method.method.replaceAll("_", " ")}`);
At the moment only the injectable operations are covered by this, 0 through 74 minus the virtual ops. 

I had thought about the more directly handled operations like voting, transfer, etc - these aren't yet supported by this PR.

The request currently accepts numbers which are matched to possible methods, we would either need an additional field like beetOperations vs injectableOperations perhaps, and pass in strings like 'transfer' etc.

2022-09-25 21:11 UTC, grctest commented on src/components/popups/linkrequestpopup.vue
> +            return types.map(type => `${type.id}: ${type.method.method.replaceAll("_", " ")}`);
RE if there are no injectables.length at the moment that's the equivalent of declaring all permissions are required, so it would be like.. 70+ op permission chips which would be displayed.

You're probably right that they won't investigate each permission, perhaps unless we provide links for each to their doc pages, but at the same time it's some helpful info for them to understand what the application may do and if there are too many chips they would ideally be wary instead of disregarding of it.

Idk if I'd want to create a like traffic light system for more ops equals bad, but you're right that we don't want to bore the user into just instantly agreeing..

I'm open to suggested improvements, perhaps some additional text to draw users attention to the permissions required?

The difference between 49 & 50 permissions could be difficult to spot, sure. Perhaps we could colour code some of the more destructive permissions? I'm not sure about just saying "this app will have all blockchain operations available to it" for "all" unless perhaps we link them to where they can find out more about all the operations they're allowing the app to prompt the user for?

2022-09-26 11:03 UTC, grctest commented on src/components/popups/linkrequestpopup.vue
> +            return types.map(type => `${type.id}: ${type.method.method.replaceAll("_", " ")}`);
Added a tooltip to each bitshares operation chip

2022-09-26 11:55 UTC, grctest commented
TODO: Include permitted operations in settings linked app table

2022-09-26 20:28 UTC, grctest commented
I've added the permitted operations to the settings table & addressed some of the todo localization, not yet tested

2022-09-28 15:55 UTC, sschiessl-bcp commented on src/components/popups/linkrequestpopup.vue
> +            return types.map(type => `${type.id}: ${type.method.method.replaceAll("_", " ")}`);
Having now this discussion, I am wondering why we need this at all? Any operation will get a popup anyways asking for permission, non?

Can you please describe the added benefit of this? I don't want to train the user to just approve the actual request popups because "the link can't do any damage anyways"

2022-09-28 16:20 UTC, grctest commented on src/components/popups/linkrequestpopup.vue
> +            return types.map(type => `${type.id}: ${type.method.method.replaceAll("_", " ")}`);
If a 3rd party application is exploited through XSS and used to launch a prompt in the background. Or if a 3rd party app is malicious/contaminated.

Sure you could simply read the existing prompt and think "I didn't ask for this, I'll reject it and report this erroneous prompt to the developer" , or an user might just click a couple buttons without reading (human error). Like users have done with proposals in the bitshares-ui interface for years.

I wouldn't want to be browsing through user created content in beet apps (and user generated beet apps), and be harassed with prompts I have no interests in. Similarly to how I don't want to let apps have location/microphone data access on my phone.

The user wouldn't need any extra training, the developer would need to include an additional field during linking to declare in advance which subset of ops they intend to use.

Reading a declaration of ops required (each with a tooltip with an explanation) is not an overbearing level of training imo.

I'm not worried about links/relinks doing damage, I'm talking about avoiding automated injected account_transfer / approve proposal scam prompts by limiting in advance the allowed scope of beet interactivity between the two apps.

2022-09-28 22:26 UTC, grctest commented on src/components/popups/linkrequestpopup.vue
> +            return types.map(type => `${type.id}: ${type.method.method.replaceAll("_", " ")}`);
More explenation in https://github.com/bitshares/beet/issues/208

2022-10-21 10:31 UTC, grctest commented on src/components/popups/linkrequestpopup.vue
> +            return types.map(type => `${type.id}: ${type.method.method.replaceAll("_", " ")}`);
@sschiessl-bcp How about putting the requested permissions in an accordion fold? https://github.com/bitshares/beet/issues/217 The PR #213 has now implemented this to improve UX when showing additional info on current prompts; this could reduce likelihood of overwhelming users with too much information

2022-11-06 10:44 UTC, sschiessl-bcp commented
Not agreeing totally with the UX / intention of this, but let's progress.

2022-11-06 10:44 UTC, sschiessl-bcp approved these changes

2022-11-06 10:45 UTC, merged

2022-11-06 14:23 UTC, sschiessl-bcp commented
Rebased to merge this one first https://github.com/bitshares/beet/pull/213, need to create new PR for those changes?

2022-11-21 21:35 UTC, grctest commented
Rebased to https://github.com/bitshares/beet/pull/222